apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: afad-statistic
  namespace: {{ .Release.Namespace }}
  labels:
    app: afad-statistic
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  rules:
    - http:
        paths:
          - path: /statistic(/|$)(.*)
            backend:
              serviceName: afad-statistic
              servicePort: 8080