kind: Service
apiVersion: v1
metadata:
  name: afad-socketio
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: afad-socketio
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: {{ .Values.service.type }}