kind: Service
apiVersion: v1
metadata:
  name: afad-system
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: afad-system
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: grpc
      protocol: TCP
      port: 6565
      targetPort: 6565
  type: {{ .Values.service.type }}