kind: Service
apiVersion: v1
metadata:
  name: afad-tiles
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: afad-tiles
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: {{ .Values.service.type }}
