apiVersion: v1
kind: ConfigMap
metadata:
  name: afad-intelligence
  namespace: {{ .Release.Namespace }}
data:
  application.yml: |
    unit.code: {{ .Values.config.unit_code }}
    scheduling:
      lock.default-lock-at-most-for: "PT5M"
      jobs:
        c125-job:
          enable: true
          lock-at-least-for: 10000
        spyder-job:
          enable: true
          connect-lock-at-least-for: 5000
          notify-lock-at-least-for: 5000
    rabbitmq:
      producer:
        system:
          exchange: system-event
          routingKey: system.event
        site:
          exchange: site-event
          routingKey: site.event
      consumer:
        system:
          routingKey: system.event.#
          queue: system.event.afad-intelligence
        site:
          routingKey: site.event.#
          queue: site.event.afad-intelligence
    # Spring
    spring:
      data:
        cassandra:
          info:
            keyspace-name: {{ .Values.config.cassandra.info.keyspace_name }}
            port: 9042
            contact-points: {{ .Values.config.cassandra.contact_points }}
            username: {{ .Values.config.cassandra.username }}
            password: {{ .Values.config.cassandra.password }}
            consistency-level: local_quorum
            serial-consistency-level: local_serial
          local:
            keyspace-name: {{ .Values.config.cassandra.local.keyspace_name }}
            port: 9042
            contact-points: {{ .Values.config.cassandra.contact_points }}
            username: {{ .Values.config.cassandra.username }}
            password: {{ .Values.config.cassandra.password }}
            consistency-level: local_quorum
            serial-consistency-level: local_serial
            local-datacenter: {{ .Values.config.cassandra.local.datacenter }}
      messages:
        basename: messages
        encoding: UTF-8
      sleuth:
        sampler:
          probability: 1
      zipkin:
        base-url: http://afad-zipkin.{{ .Release.Namespace }}:9411
      rabbitmq:
        host: {{ .Values.config.rabbitmq.host }}
        port: {{ .Values.config.rabbitmq.port }}
        username: {{ .Values.config.rabbitmq.username }}
        password: {{ .Values.config.rabbitmq.password }}
      task:
        scheduling:
          pool:
            size: 2
          shutdown:
            await-termination: true
      jackson:
        time-zone: Asia/Ho_Chi_Minh
        date-format: dd/MM/yyyy HH:mm:ss
    # ES
    es.hosts: {{ .Values.config.es_hosts }}
    # JWT
    jwt.secret: FFyeEskjbB
    # SocketIO
    socketio:
      uri: http://afad-socketio.{{ .Release.Namespace }}:8080
    # gRPC
    grpc:
      port: 6565
      shutdownGrace: 30
      channel:
        organization:
          name: afad-organization.{{ .Release.Namespace }}
          port: {{ .Values.config.grpc.organization.port }}
        category:
          name: afad-category.{{ .Release.Namespace }}
          port: {{ .Values.config.grpc.category.port }}
        missile:
          name: missile.{{ .Release.Namespace }}
          port: {{ .Values.config.grpc.missle.port }}
    # Logging
    logging:
      level:
        org.springframework.data.cassandra.core.cql: info
    # Services
    rest:
      connectTimeout: 30s
      readTimeout: 30s
      services:
        security: http://afad-security.{{ .Release.Namespace }}:8080